//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPV.Presentacion.HPV.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://schemas.datacontract.org/2004/07/HPV.Core.Dominio")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApartadoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdHotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreHotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefono1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefono2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApartadoPostal {
            get {
                return this.ApartadoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.ApartadoPostalField, value) != true)) {
                    this.ApartadoPostalField = value;
                    this.RaisePropertyChanged("ApartadoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckIn {
            get {
                return this.CheckInField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckInField, value) != true)) {
                    this.CheckInField = value;
                    this.RaisePropertyChanged("CheckIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckOut {
            get {
                return this.CheckOutField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckOutField, value) != true)) {
                    this.CheckOutField = value;
                    this.RaisePropertyChanged("CheckOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdHotel {
            get {
                return this.IdHotelField;
            }
            set {
                if ((this.IdHotelField.Equals(value) != true)) {
                    this.IdHotelField = value;
                    this.RaisePropertyChanged("IdHotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreHotel {
            get {
                return this.NombreHotelField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreHotelField, value) != true)) {
                    this.NombreHotelField = value;
                    this.RaisePropertyChanged("NombreHotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono1 {
            get {
                return this.Telefono1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefono1Field, value) != true)) {
                    this.Telefono1Field = value;
                    this.RaisePropertyChanged("Telefono1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono2 {
            get {
                return this.Telefono2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefono2Field, value) != true)) {
                    this.Telefono2Field = value;
                    this.RaisePropertyChanged("Telefono2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Direccion", Namespace="http://schemas.datacontract.org/2004/07/HPV.Core.Dominio")]
    [System.SerializableAttribute()]
    public partial class Direccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float LongitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDireccion {
            get {
                return this.IdDireccionField;
            }
            set {
                if ((this.IdDireccionField.Equals(value) != true)) {
                    this.IdDireccionField = value;
                    this.RaisePropertyChanged("IdDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/HPV.Core.Dominio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasennaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1 {
            get {
                return this.Apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido1Field, value) != true)) {
                    this.Apellido1Field = value;
                    this.RaisePropertyChanged("Apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2 {
            get {
                return this.Apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido2Field, value) != true)) {
                    this.Apellido2Field = value;
                    this.RaisePropertyChanged("Apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenna {
            get {
                return this.ContrasennaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasennaField, value) != true)) {
                    this.ContrasennaField = value;
                    this.RaisePropertyChanged("Contrasenna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HPV.Services.IServicios")]
    public interface IServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/modificarHotel", ReplyAction="http://tempuri.org/IServicios/modificarHotelResponse")]
        int modificarHotel(HPV.Presentacion.HPV.Services.Hotel hotel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/modificarHotel", ReplyAction="http://tempuri.org/IServicios/modificarHotelResponse")]
        System.Threading.Tasks.Task<int> modificarHotelAsync(HPV.Presentacion.HPV.Services.Hotel hotel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/obtenerDireccion", ReplyAction="http://tempuri.org/IServicios/obtenerDireccionResponse")]
        HPV.Presentacion.HPV.Services.Direccion obtenerDireccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/obtenerDireccion", ReplyAction="http://tempuri.org/IServicios/obtenerDireccionResponse")]
        System.Threading.Tasks.Task<HPV.Presentacion.HPV.Services.Direccion> obtenerDireccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/validarUsuario", ReplyAction="http://tempuri.org/IServicios/validarUsuarioResponse")]
        HPV.Presentacion.HPV.Services.Usuario validarUsuario(string username, string contrasenna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/validarUsuario", ReplyAction="http://tempuri.org/IServicios/validarUsuarioResponse")]
        System.Threading.Tasks.Task<HPV.Presentacion.HPV.Services.Usuario> validarUsuarioAsync(string username, string contrasenna);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosChannel : HPV.Presentacion.HPV.Services.IServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosClient : System.ServiceModel.ClientBase<HPV.Presentacion.HPV.Services.IServicios>, HPV.Presentacion.HPV.Services.IServicios {
        
        public ServiciosClient() {
        }
        
        public ServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int modificarHotel(HPV.Presentacion.HPV.Services.Hotel hotel) {
            return base.Channel.modificarHotel(hotel);
        }
        
        public System.Threading.Tasks.Task<int> modificarHotelAsync(HPV.Presentacion.HPV.Services.Hotel hotel) {
            return base.Channel.modificarHotelAsync(hotel);
        }
        
        public HPV.Presentacion.HPV.Services.Direccion obtenerDireccion() {
            return base.Channel.obtenerDireccion();
        }
        
        public System.Threading.Tasks.Task<HPV.Presentacion.HPV.Services.Direccion> obtenerDireccionAsync() {
            return base.Channel.obtenerDireccionAsync();
        }
        
        public HPV.Presentacion.HPV.Services.Usuario validarUsuario(string username, string contrasenna) {
            return base.Channel.validarUsuario(username, contrasenna);
        }
        
        public System.Threading.Tasks.Task<HPV.Presentacion.HPV.Services.Usuario> validarUsuarioAsync(string username, string contrasenna) {
            return base.Channel.validarUsuarioAsync(username, contrasenna);
        }
    }
}
